name: Main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: kperreau/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache-key-prefix: test

      - name: Verify dependencies
        run: |
          go mod verify
          git diff --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=10m

      - name: Vet
        run: make vet

      - name: Test Format
        run: |
          go install mvdan.cc/gofumpt@latest
          make format

      - name: Unit Test
        run: make ci-test